// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtC1s4qSRiB07udPdbDakuADHwL9CCMVI',
    appId: '1:386869463879:web:01d4f8bac806205fde5a62',
    messagingSenderId: '386869463879',
    projectId: 'mun-da-my-cool-project',
    authDomain: 'mun-da-my-cool-project.firebaseapp.com',
    storageBucket: 'mun-da-my-cool-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDisbu4KqUR10C_02-6h6hL0xlQ2wfsWcA',
    appId: '1:386869463879:android:f55412d0ddbeef9fde5a62',
    messagingSenderId: '386869463879',
    projectId: 'mun-da-my-cool-project',
    storageBucket: 'mun-da-my-cool-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFNCjjZ2TMpgdgheHpYicq_x3oJdmBW8',
    appId: '1:386869463879:ios:3dd1626a342a8356de5a62',
    messagingSenderId: '386869463879',
    projectId: 'mun-da-my-cool-project',
    storageBucket: 'mun-da-my-cool-project.appspot.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlFNCjjZ2TMpgdgheHpYicq_x3oJdmBW8',
    appId: '1:386869463879:ios:46cfed32eca60273de5a62',
    messagingSenderId: '386869463879',
    projectId: 'mun-da-my-cool-project',
    storageBucket: 'mun-da-my-cool-project.appspot.com',
    iosBundleId: 'com.example.diaryApp.RunnerTests',
  );
}
